version: "3.8"
services:
  web:
    build: webserver/.
    ports:
      - "8080:80"
  db:
    build: dbserver/.
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
