version: "3.8"
services:
  web:
    build: webserver/.
    ports:
      - "8080:80"
    links:
      - backend
  db:
    build: dbserver/.
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: backend/.
    ports:
      - "5000:5000"
    links:
      - db
volumes:
  pgdata: {}
